---
title: "Day 4 Exploring Data"
format: html
editor: visual
---

# Exploratory Data Viz

-   echo: don't show me the code only show me the output

```{r}
#| warning: false
#| echo: false

library(tidyverse)
library(palmerpenguins)
library(GGally)
library(skimr)
```

-   Check out data a bit:

    ```{r}
    #| include: false


    # Tell me the coloumn names

    names(penguins)

    # What are the dimension
    dim(penguins)

    # Can you show me the first six lines?
    head(penguins)

    # The last Six
    tail(penguins)
    ```

```{r}

#| echo: false

2 + 10
```

# Skim()

```{r}
# A good start for summary statistics
skim(penguins)
```

# GGally:: ggpairs()

```{r}
#| warning: false
#| echo: false

GGally::ggpairs(penguins)
```

# Jitterplot 

Flipper Length by Species

Determine something from distribution without hiding data in summary statistics

-   alpha = transparency

-   width =

```{r}

ggplot(data = penguins, aes(x = species, y = flipper_length_mm)) + geom_jitter(width = 0.2, alpha = 0.5, aes(color = species)) + geom_boxplot() + theme_light() + scale_color_manual(values = c("darkorchid4", "cyan4", "goldenrod")) + labs(x = "Penguin species", y = "Flipper lenght(mm)", title = "Palmer Penguins")
```

# Making a histogram

```{r}
ggplot(data = penguins, aes(x = bill_length_mm)) +
  geom_histogram(aes(fill = species), color = "magenta") +
  facet_wrap(~species, ncol =1)
```

\
